import {StyleSheet, Dimensions, Platform, deviceHeight} from 'react-native'
export default StyleSheet.create({
  spr_container: {
    height: Dimensions.get('window').height,
    width: Dimensions.get('window').width,
    marginTop: 0,
  },
  card1_view: {
    marginTop: 80,
    padding: 15,
    marginHorizontal: 15,
    alignItems: 'center',
    borderRadius: 15,
  },
  card1_view_txt: {
    alignItems: 'center',
    fontWeight: 'bold',
    fontSize: Dimensions.get('window').width * 0.037,
  },
  card1_btn_cont_view: {
    backgroundColor: 'transparent',
    width: 300,
    flexDirection: 'row',
    margin: 10,
    alignItems: 'center',
  },
  card1_btn_view: {
    width: 100,
    backgroundColor: 'transparent',
    padding: 7,
    justifyContent: 'center',
    alignContent: 'center',
  },
  card1_btn: {
    backgroundColor: '#5781ff',
    alignContent: 'center',
    padding: 5,
    borderRadius: 40,
  },
  card1_status: {
    width: 100,
    height: 40,
    borderLeftWidth: 0.5,
    justifyContent: 'center',
    alignContent: 'center',
  },
  card1_status_txt: {
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignSelf: 'center',
    padding: 7,
    fontWeight: 'bold',
    fontSize: 11,
  },
  card2_view: {
    marginTop: 30,
    padding: 15,
    marginHorizontal: 15,
    alignItems: 'center',
    borderRadius: 15,
  },
  card2_btn_view: {
    backgroundColor: 'transparent',
    width: 250,
    flexDirection: 'column',
    alignItems: 'center',
    margin: 5,
  },
  card2_line: {
    width: 300,
    height: 20,
    justifyContent: 'center',
    alignContent: 'center',
  },
  card2_line_txt: {
    justifyContent: 'center',
    alignSelf: 'center',
    fontWeight: 'bold',
    fontSize: 11,
  },
  creditbutton: {
    marginTop: 30,
    padding: 15,
    marginHorizontal: 15,
    alignItems: 'center',
    textAlignVertical: 'center',
    textAlign: 'center',
    borderRadius: 15,
  },
  buttonText: {
    fontSize: 14,
    color: 'black',
    letterSpacing: 1,
  },
  bottom_txt: {
    padding: 5,
    backgroundColor: 'transparent',
    borderRadius: 10,
    fontWeight: 'bold',
    fontSize: Dimensions.get('window').width * 0.03,
  },
})
