import {StyleSheet, Dimensions, Platform, deviceHeight} from 'react-native';
export default StyleSheet.create({
  spr_container: {
    // alignItems: 'center',
    marginTop: 0,
    height: Dimensions.get('window').height,
    width: Dimensions.get('window').width,
  },

  Pressable_size1: {
    backgroundColor: 'transparent',
    width: Dimensions.get('window').width * 0.1,
    height: Dimensions.get('window').height * 0.045,
    borderRadius: 5,
    alignSelf: 'center',
    justifyContent: 'center',
  },
  Pressable_size2: {
    backgroundColor: 'transparent',
    width: Dimensions.get('window').width * 0.1,
    height: Dimensions.get('window').height * 0.045,
    borderRadius: 35,
    alignSelf: 'center',
    justifyContent: 'center',
  },
  back_btn1: {
    backgroundColor: 'transparent',
    width: Dimensions.get('window').width * 0.075,
    height: Dimensions.get('window').height * 0.035,
    borderRadius: 5,
    alignSelf: 'center',
  },
  back_btn2: {
    backgroundColor: 'transparent',
    width: Dimensions.get('window').width * 0.075,
    height: Dimensions.get('window').height * 0.035,
    borderRadius: 35,
    alignSelf: 'center',
  },
  title_container: {
    marginTop: 0,
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    // backgroundColor: 'white',
    zIndex: +1,
    height: Dimensions.get('window').height * 0.065,
    width: Dimensions.get('window').width,
    borderBottomLeftRadius: 45,
    borderBottomRightRadius: 45,
    position: 'absolute',
  },
  // animateText: {
  //   fontSize: 32,
  //   fontWeight: 'bold',
  //   color: '#333',
  // },
  title_name: {
    height: Dimensions.get('window').height * 0.04,
    width: Dimensions.get('window').width * 0.6,
    fontSize: Dimensions.get('window').width * 0.065,
    color: 'black',
    justifyContent: 'center',
    textAlignVertical: 'center',
    textAlign: 'center',
    alignSelf: 'center',
    fontFamily: 'Ubuntu-Bold',
  },
  shadowa: {
    elevation: 30,
    shadowColor: '#1a00ff',
  },
  shadowi: {
    shadowColor: '#1a00ff',
    shadowOffset: {width: -2, height: 4},
    shadowOpacity: 20,
    shadowRadius: 3,
  },
  container: {
    flexDirection: 'column',
    backgroundColor: 'transparent',
    height: Dimensions.get('window').height / 1 - 62,
  },
  listContainer0: {
    marginTop: Dimensions.get('window').height * 0.08,
    width: Dimensions.get('window').width / 1.1,
    height: Dimensions.get('window').height / 1.9,
    alignSelf: 'center',
    // backgroundColor: 'red',
  },

  list_line: {
    backgroundColor: 'transparent',
    alignSelf: 'center',
  },
  item: {
    margin: 10,
    width: Dimensions.get('window').width / 1.25,
    height: Dimensions.get('window').height * 0.15,
    // padding: 0,
    borderRadius: 30,
    alignSelf: 'center',
    textAlign: 'center',
    alignItems:'center',
    justifyContent:'center',
    fontFamily: 'Ubuntu-Regular',
  },
  shadowa: {
    elevation: 30,
    shadowColor: '#1a00ff',
  },
  shadowi: {
    shadowColor: '#1a00ff',
    shadowOffset: {width: -2, height: 4},
    shadowOpacity: 20,
    shadowRadius: 3,
  },
  item2_contain: {
    marginTop: 30,
    flexDirection: 'row',
    width: Dimensions.get('window').width / 1.1,
    height: Dimensions.get('window').height * 0.17,
    backgroundColor: 'transparent',
    alignSelf: 'center',
    justifyContent: 'center',
  },
  item2: {
    margin: 10,
    width: Dimensions.get('window').width * 0.39,
    height: Dimensions.get('window').height * 0.12,
    borderRadius: 20,
    justifyContent: 'center',
    alignSelf: 'center',
    fontFamily: 'Ubuntu-Regular',
  },
  logo_txt_container: {
    width: Dimensions.get('window').width / 1.5,
    height: Dimensions.get('window').height * 0.1,
    // alignItems: 'center',
    // alignContent:'center',
    backgroundColor: 'transparent',
   justifyContent: 'flex-start',
  },
  logo_txt: {
    fontSize: Dimensions.get('window').width * 0.06,
    width: Dimensions.get('window').width / 1.5,
    // marginBottom: 10,
    marginVertical:10,
    textAlign: 'center',
    opacity: 1,
    alignSelf: 'center',
    // color: 'black',
    fontFamily: 'Ubuntu-Regular',
    backgroundColor: 'transparent',
  },
  logo_sub_txt: {
    fontSize: Dimensions.get('window').width * 0.025,
    width: Dimensions.get('window').width / 1.5,
    textAlign: 'center',
    // opacity: 0.5,
    alignSelf: 'center',
    // color: 'black',
    fontFamily: 'Ubuntu-Bold',
    backgroundColor: 'transparent',
  },
  logo_txt_containersmall: {
    width: Dimensions.get('window').width / 2.9,
    height: Dimensions.get('window').height * 0.11,
    alignSelf: 'center',
    backgroundColor: 'transparent',
    justifyContent: 'center',
    borderRadius:10
  },
  logo_sub_txtsmall: {
    fontSize: Dimensions.get('window').width * 0.029,
    width: Dimensions.get('window').width / 3,
    textAlign: 'center',
    // opacity: 0.5,
    alignSelf: 'center',
    // color: 'black',
    fontFamily: 'Ubuntu-Bold',
    backgroundColor: 'transparent',
  },
  about_img: {
    resizeMode: 'contain',
    height: Dimensions.get('window').height * 0.09,
    width: Dimensions.get('window').width / 3,
    alignSelf: 'center',
    backgroundColor: 'transparent',
    overflow: 'hidden',
  },
  noti_container: {
    width: Dimensions.get('window').width / 1.25,
    height: Dimensions.get('window').height * 0.08,
    margin: 5,
    // backgroundColor: 'white',
    alignSelf: 'center',
    borderRadius: 20,
    flexDirection: 'row',
  },
  noti_img: {
    width: Dimensions.get('window').width * 0.18,
    height: Dimensions.get('window').height * 0.08,
    alignSelf: 'center',
    borderRadius: 55,
    resizeMode: 'contain',
    backgroundColor:'transparent'
  },
  noti_text: {
    fontSize: Dimensions.get('window').width * 0.039,
    width: Dimensions.get('window').width / 1.7,
    height: Dimensions.get('window').height * 0.08,
    borderRadius: 15,
    alignSelf: 'center',
    textAlignVertical: 'center',
    textAlign: 'center',
    fontFamily: 'Ubuntu-Regular',
    backgroundColor: 'transparent',
  },
});
