import {StyleSheet, Dimensions, Platform, deviceHeight} from 'react-native'
var themecolor = '#1a00ff'
export default StyleSheet.create({
  spr_container: {
    alignItems: 'center',
    marginTop: 0,
    height: Dimensions.get('window').height,
    width: Dimensions.get('window').width,
  },
  about_img: {
    marginTop: 20,
    backgroundColor: 'transparent',
    width: Dimensions.get('window').width * 0.7,
    resizeMode: 'contain',
    height: Dimensions.get('window').height * 0.15,
    alignSelf: 'center',
  },
  name_txt1: {
    fontSize: Dimensions.get('window').width * 0.09,
    marginTop: 10,
    margin: 10,
    opacity: 1,
    textAlign: 'center',
    fontFamily: 'Ubuntu-Bold',
  },
  name_txt2: {
    fontSize: Dimensions.get('window').width * 0.03,
    marginTop: 0,
    margin: 10,
    opacity: 1,
    textAlign: 'center',
    fontFamily: 'Ubuntu-Bold',
  },
  listContainer0: {
    marginTop: 0,
    width: Dimensions.get('window').width / 1,
    height: Dimensions.get('window').height / 1 - 5,
    alignSelf: 'center',
    backgroundColor: 'transparent',
  },
  list_line: {
    alignSelf: 'center',
    backgroundColor: 'transparent',
  },
  item: {
    margin: 10,
    width: Dimensions.get('window').width / 2.5,
    height: Dimensions.get('window').height * 0.07,
    // padding: 7,
    borderRadius: 30,
    justifyContent: 'center',
    //  alignSelf:'center'
  },

  shadowa: {
    elevation: 30,
    shadowColor: '#1a00ff',
  },
  shadowi: {
    shadowColor: '#1a00ff',
    shadowOffset: {width: -2, height: 4},
    shadowOpacity: 20,
    shadowRadius: 3,
  },
  logo_txt_container: {
    width: Dimensions.get('window').width / 3,
    height: Dimensions.get('window').height * 0.05,
    alignSelf: 'center',
    textAlignVertical: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  logo_txt: {
    fontSize: Dimensions.get('window').width * 0.039,
    alignSelf: 'center',
    fontFamily: 'Ubuntu-Bold',
  },
  developer_txt3: {
    fontSize: Dimensions.get('window').width * 0.035,
    opacity: 1,
    alignSelf: 'center',
    textAlign: 'center',
    fontWeight: 'bold',
    // fontFamily: 'Ubuntu-Bold',
  },
  developer_txt2: {
    fontSize: Dimensions.get('window').width * 0.0356,
    // position:'absolute',
    // bottom:0,
    margin: 0,
    opacity: 1,
    textAlign: 'center',
    fontFamily: 'Ubuntu-Bold',
    alignSelf: 'center',
  },
  note_view: {
    width: Dimensions.get('window').width * 0.85,
    height: Dimensions.get('window').height * 0.4,
    borderRadius: 20,
    padding: 5,
    marginBottom: 10,
    alignSelf: 'center',
    justifyContent: 'center',
  },
  note_txt: {
    fontSize: Dimensions.get('window').width * 0.03,
    backgroundColor: 'transparent',
    padding: 2,
    margin: 5,
    fontWeight: 'bold',
    alignSelf: 'auto',
  },
  Scroll_txt: {
    // height: Dimensions.get('window').height * 0.25,
    backgroundColor: 'transparent',
    alignSelf: 'center',
    margin: 15,
    padding: 10,
    borderWidth: 0.6,
    borderColor: '#5d5c61',
    borderRadius: 20,
    overflow: 'hidden',
  },
  note_view_note_txt: {
    alignSelf: 'center',
    fontSize: Dimensions.get('window').width * 0.05,
    fontFamily: 'Ubuntu-Regular',
  },
  contact: {
    width: 200,
    backgroundColor: 'transparent',
    alignSelf: 'center',
    justifyContent: 'center',
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  // contact_img: {
  //   backgroundColor: 'green',
  //   width: 40,
  //   resizeMode: 'contain',
  //   height: 40,
  //   marginHorizontal:5
  // },
  contact_img2: {
    backgroundColor: 'transparent',
    width: 30,
    resizeMode: 'contain',
    height: 30,
    borderRadius: 7,
    marginHorizontal:20
  },
})
